### ISSUE TITLE
ArgoUML tries to download http://argouml.org/profiles/uml14/default-uml14.xmi

### ISSUE THREAD

**Issue by stcarrez** [argouml-tigris-org/argouml#10]
When you use your own profiles, ArgoUML tries to download the Default UML profile definition from:

```
http://argouml.org/profiles/uml14/default-uml14.xmi
```

The issue seems to be in XmiReferenceResolverImpl in toURL() in the following piece of code:

```
            if (modelUrl == null) {
                // If systemId is a valid URL, simply use it.
                // TODO: This causes a network connection attempt for profiles
                modelUrl = getValidURL(fixupURL(systemId));
            }
```

**Comment by linustolke** [comment]
So the argouml.org still points to argouml.tigris.org.

I have done the following:
* I have made the profiles that were previously at http://argouml.tigris.org/profiles/ (i.e. at http://argoum.org/profiles/) available at http://argouml-tigris-org.github.io/profiles/.
* I am trying to contact the person I suspect is owning the argouml.org domain to get it to point to the new location. I will let you know how it goes.

**Comment by linustolke** [comment]
argouml.org now point to argouml-tigris-org.github.io so this should now work.

**Comment by stcarrez** [comment]
Hi Linus,

I'm afraid you missed my point. The main issue is not on the site name.
The real issue is that ArgoUML tries to download the UML profile which it should not.
Instead of trying to download the file, it should try to load the file that is provided by the Jar that
contains it. That's the root issue.

Downloading is not a good idea because it also forces you to have an Internet
connection when you launch ArgoUML.

**Comment by linustolke** [comment]
OK. Well, yes. On the other hand referencing it with http://argouml.org/profiles/ and not downloading is confusing. Can we give them some other reference? Is there an url-standard for this kind of tool-provided files?
